export {default as Home} from './Home'
export {default as Games} from './Games'
export {default as SingleGame} from './SingleGame'
export {default as Platforms} from './Platforms'
export {default as CreatorsPage} from './CreatorsPage'
export {default as PopularPage} from './PopularPage'
export {default as PlatformGames} from './PlatformGames'